name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lucide_icons: ^0.250.0
  font_awesome_flutter: ^10.5.0
  http: 1.3.0
  url_launcher: ^6.1.10
  intl: ^0.18.1
  image_picker: ^1.0.4
  path: ^1.8.3
  animate_do: ^2.1.0
  path_provider: ^2.0.15
  flutter_secure_storage: ^9.2.4
  timeago: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/construction_bg.png
    - assets/images/background.jpg
    - assets/images/logo.jpg

